# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

class TestGiantSmokeTest():
  def setup_method(self, method):
    opts = Options()
    opts.add_argument("--headless")    
    self.driver = webdriver.Firefox(options=opts)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_giantSmokeTest(self):
    self.driver.get("http://localhost:5500/teton/1.6/index.html")
    self.driver.set_window_size(1200, 800)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
    self.driver.get("http://localhost:5500/teton/1.6/index.html")
    self.driver.set_window_size(1200, 800)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".a-button")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".a-button").click()
    self.driver.get("http://localhost:5500/teton/1.6/directory.html")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.ID, "directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member img")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "directory-list").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member img")
    assert len(elements) > 0
    self.driver.get("http://localhost:5500/teton/1.6/join.html")
    self.driver.set_window_size(1200, 800)
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("Braden")
    self.driver.find_element(By.NAME, "lname").send_keys("Roenfeldt")
    self.driver.find_element(By.NAME, "bizname").send_keys("Martian Enterprise")
    self.driver.find_element(By.NAME, "biztitle").send_keys("Martian Space Commander")
    self.driver.find_element(By.NAME, "submit").click()
    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
    self.driver.get("http://localhost:5500/teton/1.6/admin.html")
    self.driver.set_window_size(1200, 800)
    elements = self.driver.find_elements(By.NAME, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("asdf")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("asdf")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
    assert len(elements) > 0
  
